### PR TITLE
fix: no explicit client and access notebook filename

### PR DESCRIPTION
**Pull request by Kelton8Z**

### CODE REVIEW

**Comment by cristianmtr** [comment]
This fails for me

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-e250b6fac4ed> in <module>
      1 f = Flow(port_expose=12345).add(uses=CharEmbed, parallel=2).add(uses=Indexer)  # build a Flow, with 2 parallel CharEmbed, tho unnecessary
      2 with f:
----> 3     f.post('/index', DocumentArray([Document(text=t.strip()) for t in open(ipyparams.notebook_name) if t.strip()])) # index all lines of this file
      4     print(theNotebook)
      5     c.post('/search', Document(text='@request(on=something)'), on_done=print_matches)

FileNotFoundError: [Errno 2] No such file or directory: '
```

**Comment by Kelton8Z** [comment]
> This fails for me
> 
> ```
> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-6-e250b6fac4ed> in <module>
>       1 f = Flow(port_expose=12345).add(uses=CharEmbed, parallel=2).add(uses=Indexer)  # build a Flow, with 2 parallel CharEmbed, tho unnecessary
>       2 with f:
> ----> 3     f.post('/index', DocumentArray([Document(text=t.strip()) for t in open(ipyparams.notebook_name) if t.strip()])) # index all lines of this file
>       4     print(theNotebook)
>       5     c.post('/search', Document(text='@request(on=something)'), on_done=print_matches)
> 
> FileNotFoundError: [Errno 2] No such file or directory: '
> ```

changed to the approach of storing source code in a python variable to reference now

**Comment by bwanglzu** [comment]
the last cell should be a markdown instead of python code, and have you compared the result between notebook and run the readme locally?

**Comment by Kelton8Z** [comment]
> the last cell should be a markdown instead of python code, and have you compared the result between notebook and run the readme locally?

Should be fixed with the latest commit

**Review by JoanFM — APPROVED** [review]

**Pull request merged**
